package characterModel;

import java.io.File;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;

public class MFCharacter {
	String name;
	String race;
	String pfclass;
	int level;
	String alignment;
	String size;
	String type;
	Bonus init;
	Bonus AC;
	Bonus TouchAC;
	Bonus FFAC;
	// HP
	Bonus fort;
	Bonus ref;
	Bonus will;
	// Defensive Abilities
	Bonus speed;
	// Melee attacks
	// Ranged attacks
	// Special attacks
	Bonus str;
	Bonus dex;
	Bonus con;
	Bonus pfint;
	Bonus wis;
	Bonus cha;
	int BAB;
	Bonus CMB;
	Bonus CMD;
	// Feats
	// Skills
	
	// Array of skills, each of which has a name, a bonus, and two booleans for untrained and armor check.
	
	// Languages
	// SQ
	// Combat Gear
	// Other Gear
	// Other

	/**
	 * Initializes the character to default values.
	 */
	private MFCharacter() {
		name = "Dave";
		race = "Human";
		pfclass = "Barbarian";
		level = 0;
		alignment = "N";
		size = "Medium";
		type = "Humanoid (Human)";
		init = new Bonus();
		AC = new Bonus(10);
		TouchAC = new Bonus(10);
		FFAC = new Bonus(10);
		// HP
		fort = new Bonus();
		ref = new Bonus();
		will = new Bonus();
		speed = new Bonus();
		// Melee attacks
		// Ranged attacks
		// Special attacks
		str = new Bonus();
		dex = new Bonus();
		con = new Bonus();
		pfint = new Bonus();
		wis = new Bonus();
		cha = new Bonus();
		BAB = 0;
		CMB = new Bonus();
		CMD = new Bonus(10);
		// Feats
		// Skills
		// Languages
		// SQ
		// Combat Gear
		// Other Gear
		// Other
	}

	/**
	 * Gets the character's name
	 * 
	 * @return A String containing the character's name
	 */
	public String getName() {
		return new String(name);
	}

	/**
	 * Initializes the character to default values, but sets the name to the one
	 * provided
	 * 
	 * @param name - A String containing the desired name for the character.
	 */
	public MFCharacter(String name) {
		this();
		this.name = name;
	}

	/**
	 * Generates and returns a character's NPC stat block.
	 * 
	 * @return - the stat block generated by the character's stats
	 */
	public String getStatBlock() {
		StringBuilder sheet = new StringBuilder();

		sheet.append(name);
		sheet.append("\n");
		sheet.append(race);
		sheet.append(" ");
		sheet.append(pfclass);
		sheet.append(" ");
		sheet.append(level);
		sheet.append("\n");
		sheet.append(alignment);
		sheet.append(" ");
		sheet.append(size);
		sheet.append(" ");
		sheet.append(type);
		sheet.append("\nInit ");
		sheet.append(init);
		sheet.append("; Senses: Perception ");
		// Perception
		sheet.append("\n----------\nDefense\n----------\nAC ");
		sheet.append(AC);
		sheet.append(", touch ");
		sheet.append(TouchAC);
		sheet.append(", flat-footed ");
		sheet.append(FFAC);
		// Specify types of armor bonus
		sheet.append("\nhp ");
		// HP
		// Hit dice specs
		sheet.append("\nFort ");
		sheet.append(fort);
		sheet.append(", Ref ");
		sheet.append(ref);
		sheet.append(", Will ");
		sheet.append(will);
		sheet.append("\nDefensive Abilities ");
		// Defensive Abilities
		sheet.append("\n----------\nOffense\n----------\nSpeed ");
		sheet.append(speed);
		sheet.append(" ft.\nMelee ");
		// Attacks
		// Ranged attacks
		// Special attacks
		sheet.append("\n----------\nStatistics\n----------\nStr ");
		sheet.append(str);
		sheet.append(", Dex ");
		sheet.append(dex);
		sheet.append(", Con ");
		sheet.append(con);
		sheet.append(", Int ");
		sheet.append(pfint);
		sheet.append(", Wis ");
		sheet.append(wis);
		sheet.append(", Cha ");
		sheet.append(cha);
		sheet.append("\nBase Atk ");
		sheet.append(BAB);
		sheet.append("; CMB ");
		sheet.append(CMB);
		sheet.append("; CMD ");
		sheet.append(CMD);
		// Feats
		// Skills
		// Languages
		// SQ
		// Combat Gear
		// Other Gear
		// Other

		return sheet.toString();
	}

	public void loadClass(String filename) {
		// Code taken and modified from
		// https://www.mkyong.com/java/how-to-read-xml-file-in-java-dom-parser/
		try {
			File XMLFile = new File(filename);
			DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
			DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
			Document classXML = dBuilder.parse(XMLFile);
			classXML.getDocumentElement().normalize();
			Node root = classXML.getDocumentElement();

			if (root.getNodeName() != "class")
				throw new Exception("File isn't a class");

			String className = ((Element) root).getAttribute("name");

			/*
			 * Base level allows parsing of: - HD - Skills - Proficiencies - BAB - Fort -
			 * Ref - Will - SQ - SAttack - And more later
			 */

			// Add specified hit dice
			// Add classSkills first
			// add Skills per level here. This will allow us to put ranks in.
			// read all proficiencies.
			this.BAB = Integer.parseInt(getNodeText(root, "BAB"));
			this.fort.applyBonus(className, Integer.parseInt(getNodeText(root, "Fort")));
			this.ref.applyBonus(className, Integer.parseInt(getNodeText(root, "Ref")));
			this.will.applyBonus(className, Integer.parseInt(getNodeText(root, "Will")));
			// Add special qualities
			// Apply special quality bonuses
			// Add special quality effects
			// Add SAttacks
			// Add SAttack bonuses
			// Add SAttack effects
			// Add SDefense
			// Add SDefense bonuses
			// Add SDefense effects

			level++;

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private String getNodeText(Node parent, String tagName) {
		Element element = (Element) parent;

		return element.getElementsByTagName(tagName).item(0).getTextContent();
	}
	// XML Parsers

}
